spring.application.name=sbb
# DATABASE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:~/local
spring.datasource.url=jdbc:h2:~/local;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
#어떤 쿼리문이 실행되는지 보기위한
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true